# Generated by Django 3.2.3 on 2021-06-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_person_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
