# Generated by Django 3.2.3 on 2021-06-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210616_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(help_text='Author bio', max_length=1000, verbose_name='about')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.author')),
            ],
        ),
    ]
